name: ci

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [22]

    steps:
      - name: Checkout 🛎
        uses: actions/checkout@master

      - name: Setup node env 🏗
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Cache node_modules 📦
        uses: actions/cache@v4.0.2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies 👨🏻‍💻
        run: npm ci --prefer-offline --no-audit

      - name: Prepare Nuxt
        run: npx nuxt prepare

      - name: Run linter 👀
        run: npm run lint

      - name: Run prettier
        run: npx prettier --check .

      - name: Build 🚚
        if: success()
        run: npx nuxt build --preset github_pages

      - name: Upload artifact
        if: success()
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./.output/public

  deploy:
      needs: build
      permissions:
        pages: write
        id-token: write
      environment:
        name: github_pages
        url: ${{ steps.deployment.outputs.page_url }}
      runs-on: ubuntu-latest
      steps:
        - name: Deploy to GitHub Pages
          id: deployment
          uses: actions/deploy-pages@v1